### PR TITLE
Support Nuxt.js >= 2.0.0

### PR DESCRIPTION
**Pull request by rclement**
This PR aims at fixing the compatibility with Nuxt.js >= 2.0.0:

- New dependencies: `extract-text-webpack-plugin`, `friendly-errors-webpack-plugin` 
- New dev-dependency: `@nuxt/common`
- Replace usage of `r()` and `urlJoin()` from `nuxt` using the `@nuxt/common` package
- Update `webpack` config
    - Replace `module.loaders` with `module.rules`
    - Resolve `CHUNK_FILENAME` as a string, depending on Nuxt build configuration

This fixes issues #104 and #105.
This can be tested using the `@rmnclmnt/nuxt-netlify-cms` package.

### CODE REVIEW

**Comment by medfreeman** [comment]
thanks! also closes #60

**Comment by rclement** [comment]
@medfreeman here are the latest enhancements to this PR:

- I merged back your upstream changes in master branch to resolve conflicts in `package.json`
- Following the advice in #60, I replaced `extract-text-webpack-plugin` (deprecated) with `mini-css-extract-plugin` for webpack v4 compatibility

Feel free to comment on this!
Thanks!

**Comment by medfreeman** [comment]
Hi !
Sorry but it seems my circleci settings do not build forked pull requests.
Thanks for the work, but the commits aren't enough since they do not pass tests at all.
I pretty much finished the work while keeping your commit in the [rclement-support-nuxt-2.0 branch](https://github.com/medfreeman/nuxt-netlify-cms-module/compare/master...rclement-support-nuxt-2.0).

I used `extract-css-chunks-webpack-plugin`, as nuxt 2.0 does.

**Comment by medfreeman** [comment]
I'm testing the example atm, and will update test snapshots then merge to master.
I'll also keep the previous code in @nuxt1 branch.

**Comment by medfreeman** [comment]
Oh, it seems i need webpack bar, and a way to register the `admin` compiler in nuxt compilers to streamline the output also.

**Comment by medfreeman** [comment]
closing in favor of #111

**Pull request closed without merging**
